
#ifndef HWX_CODEEX_H
#define HWX_CODEEX_H
#include "XTypeEx.h"



#ifdef __cplusplus
extern "C"{
#endif 
	DLLXEXPORT LONG WINAPI UTF16ToUTF8(LPCWSTR pszUTF16, LPSTR pszUTF8);
	DLLXEXPORT LONG WINAPI UTF8ToUTF16(const CHAR *src, LPWSTR pszUTF16);
	DLLXEXPORT LONG WINAPI TCToSC(LPCWSTR, LPWSTR);	
	DLLXEXPORT LONG WINAPI SCToTC(LPCWSTR, LPWSTR);	
	DLLXEXPORT LONG WINAPI HalfToFull(LPCWSTR, LPWSTR);
#ifdef __cplusplus
}
#endif
	

#endif //HWX_CODEEX_H